default_environment: dev
project_id: 019e73d5-1a45-7e19-996b-fe6427e2ae92
environments:
- name: dev
- name: staging
- name: prod
python: python3.11
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      host: aws-1-ap-northeast-1.pooler.supabase.com
      port: 5432
      user: postgres.wracqytxbmhkbrfcvwew
    select:
    - public-resale_flat_prices_from_jan_2017.*
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git setuptools<80
    config:
      batch_size: 104857600
      credentials_path: /home/liuyx/5m-data-2.6-data-pipelines-orchestration/my-project-learning-496207-d95254168283.json
      dataset: resale
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: my-project-learning-496207
